# Generated by Django 4.2.11 on 2024-04-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
