# Generated by Django 4.2.11 on 2024-04-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesapp', '0004_remove_post_caption_remove_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileimg',
        ),
    ]
