# Generated by Django 4.2.11 on 2024-04-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesapp', '0006_alter_post_created_alter_post_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
